epochs: 10
models: mlp
result_folder: /home/cossu/experiments/mnist/test

# TASK CONFIGURATION
n_tasks: 5
output_size: 10
input_size: 1
max_label_value: 10 # if real value is greater, a % op will be applied on it.

# OPTIMIZER
weight_decay: 0
learning_rate: 3e-05
batch_size: 32
clip_grad: 5.0

# EXTRAS
job_id: -1 # if >= 0 execute validation over multiple nodes. Need to configure `distributed_validation.csv`.')
multitask: false
multihead: false
test_on_val: true
not_test: false
not_intermediate_test: false
monitor: true # monitor metrics
save: true # save models
load: false # load previous models
cuda: true

# MODELS
expand_output: 0 #Expand output layer dynamically

# RNN - LSTM - LMN
hidden_size_rnn: 128
layers_rnn: 1
hidden_size_lmn: 128 # hidden dimension of functional component of LMN
memory_size_lmn: 128 # memory size of LMN
functional_out: true # compute output from functional instead of memory')
orthogonal: false # Use orthogonal recurrent matrixes

# MLP
hidden_sizes_mlp: # number of hidden units for each layer
 - 128
relu_mlp: true # tanh if false

# LWTA
units_per_block: # number of units per block for each hidden layer
  - 3
blocks_per_layer: # number of blocks for each hidden layer
 - 10
activation_lwta: relu # relu, tanh, none

# ESN
reservoir_size: 128
spectral_radius: 0.9
sparsity: 0.0
alpha: 1.0
orthogonal_esn: false # Using orthogonal reservoir

# CNN
feed_conv_layers: # units for each feedforward layers of CNN
 - 256
 - 128
n_conv_layers: 3 # number of convolutional layers

# MNIST
split: true # Use split MNIST
sequential: false # permute images

# CL STRATEGIES
ewc_lambda: 0 
mas_lambda: 0
cwr: false
ar1: false
lwf: false
lwf_temp: 1 # softmax temperature for LwF
warmup_epochs: 0 # how many warmup epochs for lwf
si_lambda: 0
eps: 1e-3 # SI epsilon
rehe_patterns: 0 # Number of rehearsal patterns per class
truncated_time: 0 # Truncated time when computing importance gradient